name: release-drafter/release-drafter@v5
on:
  push:
    branches:
      - main
jobs:
  release_draft:
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      #  TODO: Uncomment this step when using GitHub Enterprise
      #- name: Set GHE_HOST for GitHub Enterprise
      #   run: echo "GHE_HOST=${GITHUB_SERVER_URL##https:\/\/}" >> $GITHUB_ENV

      - name: release-drafter/release-drafter@v5
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
